server:
  port: 15688
spring:
  datasource:
    username: root
    password: data19
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cdvs0gsza8rk.ap-northeast-2.rds.amazonaws.com:3306/news?useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
