spring:
  datasource:
    username: limc
    password: data19
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/news?useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect